on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Build and deploy GitHub Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_ONLY: true
          # PAGES_BRANCH: gh-pages
          # TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: copy fork-awesome includes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd public
          sudo cp -r ./ForkAwesome/src/doc/_includes .
          sudo git init
          sudo git config --global user.email "action@github.com"
          sudo git config --global user.name "GitHub Action"
          sudo git add .
          sudo git commit -m "Deploy to GitHub Pages"
      
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true